# Base image
FROM node:18.16.0

# Set working directory in container
WORKDIR /usr/src/app

# Copy all 
COPY . /usr/src/app/

# Install dependencies
RUN npm install

# Expose port 8080 (the one your app uses)
EXPOSE 8080

# Command to start the application
CMD ["npm", "start"]
